In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/kaggle/input/datasets/anubhavsingh311/food-delivery-dataset/train.csv")
print(df.shape[0])
print(df.shape[1])

45593
20

In [3]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

In [4]:
df.isna().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

In [5]:
#Cleaning Part
df_temp = df.copy()
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  object
 1   Delivery_person_ID           45593 non-null  object
 2   Delivery_person_Age          45593 non-null  object
 3   Delivery_person_Ratings      45593 non-null  object
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  object
 9   Time_Orderd                  45593 non-null  object
 10  Time_Order_picked            45593 non-null  object
 11  Weatherconditions            45593 non-null  object
 12  Road_traffic_density         45593 non-null  object
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  object
 15  Type_of_vehicle              45593 non-null  object
 16  multiple_deliveries          45593 non-null  object
 17  Festival                     45593 non-null  object
 18  City                         45593 non-null  object
 19  Time_taken(min)              45593 non-null  object
dtypes: float64(4), int64(1), object(15)
memory usage: 7.0+ MB

In [6]:
for col in df_temp.select_dtypes(include="object").columns:
    df_temp[col] = df_temp[col].str.strip()

In [7]:
df_temp = df_temp.replace("NaN", np.nan)
df_temp.isin(["NaN"]).any()

ID                             False
Delivery_person_ID             False
Delivery_person_Age            False
Delivery_person_Ratings        False
Restaurant_latitude            False
Restaurant_longitude           False
Delivery_location_latitude     False
Delivery_location_longitude    False
Order_Date                     False
Time_Orderd                    False
Time_Order_picked              False
Weatherconditions              False
Road_traffic_density           False
Vehicle_condition              False
Type_of_order                  False
Type_of_vehicle                False
multiple_deliveries            False
Festival                       False
City                           False
Time_taken(min)                False
dtype: bool

In [8]:
df_temp["Weatherconditions"].value_counts()

Weatherconditions
conditions Fog           7654
conditions Stormy        7586
conditions Cloudy        7536
conditions Sandstorms    7495
conditions Windy         7422
conditions Sunny         7284
conditions NaN            616
Name: count, dtype: int64

In [9]:
df_temp["Weatherconditions"] = df_temp["Weatherconditions"].replace("conditions NaN", np.nan)
df_temp["Weatherconditions"] = df_temp["Weatherconditions"].replace("conditions Fog", "Fog")
df_temp["Weatherconditions"] = df_temp["Weatherconditions"].replace("conditions Stormy", "Stormy")
df_temp["Weatherconditions"] = df_temp["Weatherconditions"].replace("conditions Cloudy", "Cloudy")
df_temp["Weatherconditions"] = df_temp["Weatherconditions"].replace("conditions Sandstorms", "Sandstorms")
df_temp["Weatherconditions"] = df_temp["Weatherconditions"].replace("conditions Windy", "Windy")
df_temp["Weatherconditions"] = df_temp["Weatherconditions"].replace("conditions Sunny", "Sunny")
df_temp.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

In [10]:
df_temp["Delivery_person_Age"] = pd.to_numeric(
    df_temp["Delivery_person_Age"],
    errors="coerce"
)

df_temp["Delivery_person_Ratings"] = pd.to_numeric(
    df_temp["Delivery_person_Ratings"],
    errors="coerce"
)

df_temp["multiple_deliveries"] = pd.to_numeric(
    df_temp["multiple_deliveries"],
    errors="coerce"
)

In [11]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  object
 1   Delivery_person_ID           45593 non-null  object
 2   Delivery_person_Age          43739 non-null  float64
 3   Delivery_person_Ratings      43685 non-null  float64
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  object
 9   Time_Orderd                  43862 non-null  object
 10  Time_Order_picked            45593 non-null  object
 11  Weatherconditions            44977 non-null  object
 12  Road_traffic_density         44992 non-null  object
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  object
 15  Type_of_vehicle              45593 non-null  object
 16  multiple_deliveries          44600 non-null  float64
 17  Festival                     45365 non-null  object
 18  City                         44393 non-null  object
 19  Time_taken(min)              45593 non-null  object
dtypes: float64(7), int64(1), object(12)
memory usage: 7.0+ MB

In [12]:
df_temp["Time_taken(min)"] = (
    df_temp["Time_taken(min)"]
    .str.replace("(min)", "", regex=False)
    .str.strip()
)

df_temp["Time_taken(min)"] = pd.to_numeric(
    df_temp["Time_taken(min)"],
    errors="coerce"
)

In [13]:
df_temp["Time_taken(min)"].head()

0    24
1    33
2    26
3    21
4    30
Name: Time_taken(min), dtype: int64

In [14]:
df_temp["Order_Date"] = pd.to_datetime(
    df_temp["Order_Date"],
    format="%d-%m-%Y",
    errors="coerce"
)
df_temp["Time_Orderd"] = pd.to_datetime(
    df_temp["Time_Orderd"],
    format="%H:%M:%S",
    errors="coerce"
)

df_temp["Time_Order_picked"] = pd.to_datetime(
    df_temp["Time_Order_picked"],
    format="%H:%M:%S",
    errors="coerce"
)

In [15]:
df_temp.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,1900-01-01 11:30:00,1900-01-01 11:45:00,Sunny,High,2,Snack,motorcycle,0.0,No,Urban,24
1,0xb379,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,1900-01-01 19:45:00,1900-01-01 19:50:00,Stormy,Jam,2,Snack,scooter,1.0,No,Metropolitian,33
2,0x5d6d,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,1900-01-01 08:30:00,1900-01-01 08:45:00,Sandstorms,Low,0,Drinks,motorcycle,1.0,No,Urban,26
3,0x7a6a,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,1900-01-01 18:00:00,1900-01-01 18:10:00,Sunny,Medium,0,Buffet,motorcycle,1.0,No,Metropolitian,21
4,0x70a2,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,1900-01-01 13:30:00,1900-01-01 13:45:00,Cloudy,High,1,Snack,scooter,1.0,No,Metropolitian,30

In [16]:
print("Missing values:")
print(df_temp.isna().sum())

Missing values:
ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weatherconditions               616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken(min)                   0
dtype: int64

In [17]:
df_temp["Delivery_person_Age"] = df_temp["Delivery_person_Age"].fillna(df_temp["Delivery_person_Age"].median())
df_temp["Delivery_person_Age"].isna().sum()

np.int64(0)

In [18]:
df_temp["Delivery_person_Ratings"] = df_temp["Delivery_person_Ratings"].fillna(df_temp["Delivery_person_Ratings"].median())
df_temp["Delivery_person_Ratings"].isna().sum()

np.int64(0)

In [19]:
df_temp["multiple_deliveries"] = df_temp["multiple_deliveries"].fillna(df_temp["multiple_deliveries"].mode()[0])
df_temp["multiple_deliveries"].isna().sum()

np.int64(0)

In [20]:
df_temp["Weatherconditions"] = df_temp["Weatherconditions"].fillna("Unknown")
df_temp["Road_traffic_density"] = df_temp["Road_traffic_density"].fillna("Unknown")
df_temp["Festival"] = df_temp["Festival"].fillna("Unknown")
df_temp["City"] = df_temp["City"].fillna("Unknown")
df_temp.isna().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age               0
Delivery_person_Ratings           0
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weatherconditions                 0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries               0
Festival                          0
City                              0
Time_taken(min)                   0
dtype: int64

In [21]:
#Feature Engineering
#1) Calculating distance using Haversine formula
def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371 

    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)
    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = (
        np.sin(dlat / 2) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
    )

    c = 2 * np.arcsin(np.sqrt(a))

    return R * c

In [22]:
df_temp["distance_km"] = haversine_distance(
    df_temp["Restaurant_latitude"],
    df_temp["Restaurant_longitude"],
    df_temp["Delivery_location_latitude"],
    df_temp["Delivery_location_longitude"]
)

In [23]:
df_temp.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min),distance_km
0,0x4607,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,1900-01-01 11:30:00,...,Sunny,High,2,Snack,motorcycle,0.0,No,Urban,24,3.025149
1,0xb379,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,1900-01-01 19:45:00,...,Stormy,Jam,2,Snack,scooter,1.0,No,Metropolitian,33,20.183530
2,0x5d6d,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,1900-01-01 08:30:00,...,Sandstorms,Low,0,Drinks,motorcycle,1.0,No,Urban,26,1.552758
3,0x7a6a,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,1900-01-01 18:00:00,...,Sunny,Medium,0,Buffet,motorcycle,1.0,No,Metropolitian,21,7.790401
4,0x70a2,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,1900-01-01 13:30:00,...,Cloudy,High,1,Snack,scooter,1.0,No,Metropolitian,30,6.210138

In [24]:
df_temp["distance_km"].describe()

count    45593.000000
mean        99.303911
std       1099.731281
min          1.465067
25%          4.663493
50%          9.264281
75%         13.763977
max      19692.674606
Name: distance_km, dtype: float64

In [25]:
Q1 = df_temp["distance_km"].quantile(0.25)
Q3 = df_temp["distance_km"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df_temp = df_temp[(df_temp["distance_km"] >= lower_bound) & (df_temp["distance_km"] <= upper_bound)].copy()
df_temp["distance_km"].describe()

count    45162.000000
mean         9.735396
std          5.608508
min          1.465067
25%          4.663412
50%          9.220209
75%         13.681490
max         20.969489
Name: distance_km, dtype: float64

In [26]:
print(len(df)- len(df_temp))

431

In [27]:
df_temp["Order_Hour"] = df_temp["Time_Orderd"].dt.hour
df_temp["Order_Minute"] = df_temp["Time_Orderd"].dt.minute

df_temp["Order_Day"] = df_temp["Order_Date"].dt.day
df_temp["Order_Month"] = df_temp["Order_Date"].dt.month
df_temp["Order_DayOfWeek"] = df_temp["Order_Date"].dt.dayofweek

df_temp.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,multiple_deliveries,Festival,City,Time_taken(min),distance_km,Order_Hour,Order_Minute,Order_Day,Order_Month,Order_DayOfWeek
0,0x4607,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,1900-01-01 11:30:00,...,0.0,No,Urban,24,3.025149,11.0,30.0,19,3,5
1,0xb379,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,1900-01-01 19:45:00,...,1.0,No,Metropolitian,33,20.183530,19.0,45.0,25,3,4
2,0x5d6d,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,1900-01-01 08:30:00,...,1.0,No,Urban,26,1.552758,8.0,30.0,19,3,5
3,0x7a6a,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,1900-01-01 18:00:00,...,1.0,No,Metropolitian,21,7.790401,18.0,0.0,5,4,1
4,0x70a2,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,1900-01-01 13:30:00,...,1.0,No,Metropolitian,30,6.210138,13.0,30.0,26,3,5

In [28]:
def get_time_period(hour):
    if 6 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

df_temp["Time_Period"] = df_temp["Order_Hour"].apply(get_time_period)

df_temp["Time_Period"].value_counts()

Time_Period
Evening      17833
Night        15605
Morning       7690
Afternoon     4034
Name: count, dtype: int64

In [29]:
df_temp["Is_Weekend"] = df_temp["Order_DayOfWeek"].isin([5, 6]).astype(int)
df_temp["Is_Weekend"].value_counts()

Is_Weekend
0    32734
1    12428
Name: count, dtype: int64

In [30]:
df_temp["Time_taken(min)"].describe()

count    45162.000000
mean        26.298038
std          9.383733
min         10.000000
25%         19.000000
50%         26.000000
75%         32.000000
max         54.000000
Name: Time_taken(min), dtype: float64

In [31]:
categorical_cols = df_temp.select_dtypes(include="object").columns

for col in categorical_cols:
    print(df_temp[col].value_counts())

ID
0x5fb2    1
0x4607    1
0xb379    1
0x5d6d    1
0x7a6a    1
         ..
0x3af3    1
0xdb64    1
0xc8b6    1
0x2784    1
0xd987    1
Name: count, Length: 45162, dtype: int64
Delivery_person_ID
PUNERES01DEL01      67
JAPRES11DEL02       67
JAPRES03DEL01       66
VADRES11DEL02       66
RANCHIRES02DEL01    66
                    ..
KOLRES04DEL03        7
KOCRES16DEL03        6
KOLRES09DEL03        6
KOLRES010DEL03       6
BHPRES010DEL03       5
Name: count, Length: 1320, dtype: int64
Weatherconditions
Fog           7604
Stormy        7544
Cloudy        7485
Sandstorms    7442
Windy         7382
Sunny         7238
Unknown        467
Name: count, dtype: int64
Road_traffic_density
Low        15372
Jam        14050
Medium     10886
High        4400
Unknown      454
Name: count, dtype: int64
Type_of_order
Snack     11428
Meal      11332
Drinks    11225
Buffet    11177
Name: count, dtype: int64
Type_of_vehicle
motorcycle          26236
scooter             15125
electric_scooter     3750
bicycle                51
Name: count, dtype: int64
Festival
No         44048
Yes          886
Unknown      228
Name: count, dtype: int64
City
Metropolitian    33785
Urban            10032
Unknown           1183
Semi-Urban         162
Name: count, dtype: int64
Time_Period
Evening      17833
Night        15605
Morning       7690
Afternoon     4034
Name: count, dtype: int64

In [32]:
print("Shape:", df_temp.shape)

print("\nMissing values:")
print(df_temp.isna().sum())

print("\nDuplicate rows:", df_temp.duplicated().sum())

print("\nDuplicate IDs:", df_temp["ID"].duplicated().sum())

print("\nData types:")
print(df_temp.dtypes)

Shape: (45162, 28)

Missing values:
ID                                0
Delivery_person_ID                0
Delivery_person_Age               0
Delivery_person_Ratings           0
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1456
Time_Order_picked                 0
Weatherconditions                 0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries               0
Festival                          0
City                              0
Time_taken(min)                   0
distance_km                       0
Order_Hour                     1456
Order_Minute                   1456
Order_Day                         0
Order_Month                       0
Order_DayOfWeek                   0
Time_Period                       0
Is_Weekend                        0
dtype: int64

Duplicate rows: 0

Duplicate IDs: 0

Data types:
ID                                     object
Delivery_person_ID                     object
Delivery_person_Age                   float64
Delivery_person_Ratings               float64
Restaurant_latitude                   float64
Restaurant_longitude                  float64
Delivery_location_latitude            float64
Delivery_location_longitude           float64
Order_Date                     datetime64[ns]
Time_Orderd                    datetime64[ns]
Time_Order_picked              datetime64[ns]
Weatherconditions                      object
Road_traffic_density                   object
Vehicle_condition                       int64
Type_of_order                          object
Type_of_vehicle                        object
multiple_deliveries                   float64
Festival                               object
City                                   object
Time_taken(min)                         int64
distance_km                           float64
Order_Hour                            float64
Order_Minute                          float64
Order_Day                               int32
Order_Month                             int32
Order_DayOfWeek                         int32
Time_Period                            object
Is_Weekend                              int64
dtype: object

In [33]:
def get_time_period(hour):
    if pd.isna(hour):
        return "Unknown"
    elif 6 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"


df_temp["Time_Period"] = df_temp["Order_Hour"].apply(get_time_period)
df_temp["Time_Period"].value_counts()

Time_Period
Evening      17833
Night        14149
Morning       7690
Afternoon     4034
Unknown       1456
Name: count, dtype: int64

In [34]:
df_temp["Time_Order_Missing"] = df_temp["Time_Orderd"].isna().astype(int)
df_temp["Time_Order_Missing"].value_counts()

Time_Order_Missing
0    43706
1     1456
Name: count, dtype: int64

In [35]:
df_temp["Order_Hour"] = df_temp["Order_Hour"].fillna(df_temp["Order_Hour"].median())
df_temp["Order_Minute"] = df_temp["Order_Minute"].fillna(df_temp["Order_Minute"].median())
df_temp[["Order_Hour", "Order_Minute"]].isna().sum()

Order_Hour      0
Order_Minute    0
dtype: int64

In [36]:
#Pickup delay time calc FE
df_temp["Pickup_Delay_Min"] = (df_temp["Time_Order_picked"] - df_temp["Time_Orderd"]).dt.total_seconds() / 60
df_temp["Pickup_Delay_Missing"] = df_temp["Pickup_Delay_Min"].isna().astype(int)
df_temp["Pickup_Delay_Min"].describe()

count    43706.000000
mean       -17.323251
std        196.229808
min      -1435.000000
25%          5.000000
50%         10.000000
75%         15.000000
max         15.000000
Name: Pickup_Delay_Min, dtype: float64

In [37]:
df_temp["Pickup_Delay_Min"] = df_temp["Pickup_Delay_Min"].fillna(df_temp["Pickup_Delay_Min"].median())
df_temp["Pickup_Delay_Min"].isna().sum()

np.int64(0)

In [38]:
print("Negative pickup delays:")
print((df_temp["Pickup_Delay_Min"] < 0).sum())

print("\nPickup delay statistics:")
print(df_temp["Pickup_Delay_Min"].describe())

Negative pickup delays:
829

Pickup delay statistics:
count    45162.000000
mean       -16.442363
std        193.100971
min      -1435.000000
25%          5.000000
50%         10.000000
75%         15.000000
max         15.000000
Name: Pickup_Delay_Min, dtype: float64

In [39]:
df_temp["Pickup_Hour"] = df_temp["Time_Order_picked"].dt.hour
df_temp["Pickup_Minute"] = df_temp["Time_Order_picked"].dt.minute
df_temp[["Pickup_Hour", "Pickup_Minute"]].isna().sum()

Pickup_Hour      0
Pickup_Minute    0
dtype: int64

In [40]:
df_temp["Pickup_Time_Period"] = df_temp["Pickup_Hour"].apply(get_time_period)
df_temp["Pickup_Time_Period"].value_counts()

Pickup_Time_Period
Evening      17707
Night        15455
Morning       7572
Afternoon     4428
Name: count, dtype: int64

In [41]:
# Correct midnight rollover in pickup delay
df_temp.loc[df_temp["Pickup_Delay_Min"] < 0,"Pickup_Delay_Min"] += 24 * 60

In [42]:
print("Negative pickup delays:",
      (df_temp["Pickup_Delay_Min"] < 0).sum())

print("Pickup delay statistics:")
print(df_temp["Pickup_Delay_Min"].describe())

Negative pickup delays: 0
Pickup delay statistics:
count    45162.000000
mean         9.990479
std          4.021311
min          5.000000
25%          5.000000
50%         10.000000
75%         15.000000
max         15.000000
Name: Pickup_Delay_Min, dtype: float64

In [43]:
print(df_temp["Pickup_Delay_Min"].isna().sum())

0

In [44]:
numeric_cols = [
    "Delivery_person_Age",
    "Delivery_person_Ratings",
    "distance_km",
    "Pickup_Delay_Min"
]

for col in numeric_cols:
    Q1 = df_temp[col].quantile(0.25)
    Q3 = df_temp[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = ((df_temp[col] < lower_bound) |
                (df_temp[col] > upper_bound)).sum()

    print(f"{col}: {outliers}")

Delivery_person_Age: 31
Delivery_person_Ratings: 2453
distance_km: 0
Pickup_Delay_Min: 0

In [45]:
Q1 = df_temp["distance_km"].quantile(0.25)
Q3 = df_temp["distance_km"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df_temp = df_temp[(df_temp["distance_km"] >= lower_bound) & (df_temp["distance_km"] <= upper_bound)]

In [46]:
Q1 = df_temp["Delivery_person_Age"].quantile(0.25)
Q3 = df_temp["Delivery_person_Age"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

before = len(df_temp)

df_temp = df_temp[
    (df_temp["Delivery_person_Age"] >= lower_bound) &
    (df_temp["Delivery_person_Age"] <= upper_bound)
]

after = len(df_temp)

print("Rows removed:", before - after)
print("Shape:", df_temp.shape)

Rows removed: 31
Shape: (45131, 34)

In [47]:
Q1 = df_temp["Delivery_person_Ratings"].quantile(0.25)
Q3 = df_temp["Delivery_person_Ratings"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

before = len(df_temp)

df_temp = df_temp[
    (df_temp["Delivery_person_Ratings"] >= lower_bound) &
    (df_temp["Delivery_person_Ratings"] <= upper_bound)
]

after = len(df_temp)

print("Rows removed:", before - after)
print("New shape:", df_temp.shape)

Rows removed: 2422
New shape: (42709, 34)

In [48]:
outliers = ((df_temp["Delivery_person_Ratings"] < lower_bound) | (df_temp["Delivery_person_Ratings"] > upper_bound)).sum()
print("Remaining outliers:", outliers)

Remaining outliers: 0